language: node_js
node_js:
  - "8"
before_install:
 - npm install -g hexo-cli
install:
 - npm install
before_script:
 - hexo clean
 - hexo generate
script: 
 - git config user.name "wangbaogang"
 - git config user.email "1371069685@qq.com"
 - sed -i "s/gh_token/${GH_TOKEN}/g" _config.yml
 - echo GH_TOKEN
 - hexo deploy



